---
name: tree-sitter-cli-static
description: |
  The Tree-sitter CLI allows you to develop, test, and use Tree-sitter grammars from the command line. It works on
  MacOS, Linux, and Windows.
homepage: https://github.com/tree-sitter/tree-sitter/blob/master/cli/README.md
licenses:
  - MIT
languages: []
categories:
  - Compiler

source:
  id: pkg:generic/tree-sitter/tree-sitter@v0.25.10
  download:
    - target: linux_x64
      url: https://github.com/PEMessage/mason-registry/raw/refs/heads/main/packages/tree-sitter-cli/prebuilt/tree-sitter-linux-x64
      file: tree-sitter-linux-x64
      bin: tree-sitter-linux-x64

bin:
  tree-sitter: "{{source.download.bin}}"
